apiVersion: v1
kind: Service
metadata:
  name: web
  labels:
    service: web
spec:
  type: NodePort
  ports:
  - name: http
    port: 8080
    targetPort: 8080
    nodePort: 30001
  selector:
    service: web
